# https://starship.rs/config/
# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false
command_timeout = 2000
format="""$os$all"""

[character]
# Prompt character not necessary with Warp if in mode where prompt is already split onto a new line
# Error is highlighted
# disabled = true
success_symbol = '[➜](bold green)'
error_symbol = '[➜](bold red)'

[os]
format = '[$symbol](bold white) '   
disabled = false

[os.symbols]
Windows = ' '
Arch = '󰣇'
Ubuntu = ''
Macos = '󰀵'

[directory]
style = 'bold bright-black'

[git_branch]
symbol = ' '
style = 'bold blue'

[git_status]
disabled = true
format = '([$staged$modified$deleted]($style) )'
stashed = ''
renamed = ''
staged = ''
modified = ''
deleted = ''
style='bold purple'

[bun]
symbol = '🥟 '

[golang]
symbol = 'go '

[package]
disabled = true

[python]
symbol = '󰌠 '

[gcloud]
disabled = true 
